---
version: '3.8'

services:
  jenkins:
    image: waterticket/jenkins-withdocker-all-architecture:latest
    container_name: jenkins
    privileged: true
    restart: unless-stopped
    ports:
      - "9090:8080"
    volumes:
      - ./data/:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock:ro
