name: Update
on:
  schedule:
    # update every monday, 00:00 -> 09:00 (GMT+9)
    - cron: "0 0 * * 1"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check new jenkins docker update date
        run: |
          hub_last_update_date=$(curl -s https://hub.docker.com/v2/namespaces/jenkins/repositories/jenkins/tags?page_size=100 | jq -r '.results[] | select(.name == "lts-jdk17") | .last_updated')
          echo "hub_last_update_date: $hub_last_update_date"

      - name: Get current update date
        run: |
          last_update_date=$(cat last_update_date.txt)
          echo "last_update_date: $last_update_date"

      - id: check_update
        name: Check if new update is available
        run: |
          if [ "$hub_last_update_date" != "$last_update_date" ]; then
            echo "New update found!"
            echo "UPDATE_PROCESS=true" >> $GITHUB_ENV
          else
            echo "No new updates found."
            echo "UPDATE_PROCESS=false" >> $GITHUB_ENV
          fi

      - name: Get jenkins version
        if: env.UPDATE_PROCESS == 'true'
        run: |
          docker pull jenkins/jenkins:lts-jdk17
          jenkins_version=$(docker inspect jenkins/jenkins:lts-jdk17 --format '{{ index .Config.Labels "org.opencontainers.image.version" }}')
          echo "Jenkins version: $jenkins_version"

      - name: Docker Setup QEMU
        if: env.UPDATE_PROCESS == 'true'
        uses: docker/setup-qemu-action@v1.2.0

      - name: Docker Setup Buildx
        if: env.UPDATE_PROCESS == 'true'
        uses: docker/setup-buildx-action@v1.6.0

      - name: Docker Login
        if: env.UPDATE_PROCESS == 'true'
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Build Image with version tag
        if: env.UPDATE_PROCESS == 'true'
        run: docker buildx build --platform linux/arm64,linux/amd64 --push --tag waterticket/jenkins-withdocker-all-architecture:${jenkins_version} .

      - name: Build Image with latest tag
        if: env.UPDATE_PROCESS == 'true'
        run: docker buildx build --platform linux/arm64,linux/amd64 --push --tag waterticket/jenkins-withdocker-all-architecture:latest .

      - name: Save new update date
        if: env.UPDATE_PROCESS == 'true'
        run: echo $hub_last_update_date > last_update_date.txt

      - name: Set date in environment variable
        run: echo "DATE=$(date +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV

      - name: Commit & Push changes
        uses: Andro999b/push@patch-1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          message: >
            chore: check new updates for ${{ env.DATE }}
